import { initialize, scheduleRequest, getAccess, login, logout, onAuthChange } from './supabase.js';
let isAdmin=false,currentUser=null;

const $=id=>document.getElementById(id),days=['','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=[],page='professors',view='week',editing=null,loaded=false;
const source=()=>records;
async function api(path,options={}){return scheduleRequest(path,options);}
async function load(){try{records=(await api('/api/sessions')).sessions;loaded=true;$('status').hidden=true;updateFilters();renderContent();}catch(e){$('status').hidden=false;$('status').className='notice error';$('status').innerHTML='<span>'+esc(e.message)+'</span><button onclick="load()">Retry</button>';$('content').className='empty';$('content').innerHTML='<h2>Timetable unavailable</h2><p>Use Retry above to load your schedule.</p>';}}
function updateFilters(){const list=source();for(const [id,key,label] of [['professorFilter','professor','All professors'],['groupFilter','groups','All groups']]){const old=$(id).value;const vals=[...new Set(list.flatMap(r=>key==='groups'?r.groups:[r[key]]))].sort();$(id).innerHTML='<option value="">'+label+'</option>'+vals.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('');if(vals.includes(old))$(id).value=old;}
$('professorNames').innerHTML=[...new Set(records.map(r=>r.professor))].map(v=>'<option value="'+esc(v)+'">').join('');$('roomNames').innerHTML=[...new Set(records.map(r=>r.room))].map(v=>'<option value="'+esc(v)+'">').join('');}
function navigate(next){if(next==='schedule'||next==='rooms')next='professors';if(next==='admin'&&!isAdmin){if(!currentUser)$('loginDialog').showModal();else toast('This account has view access.');return;}page=next;location.hash=next;$('title').textContent=page==='admin'?'Manage classes':'Professors';document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('viewbar').hidden=page==='admin';$('filters').hidden=false;$('legend').hidden=page==='admin';resetFilters(false);updateFilters();renderContent();}
function resetFilters(render=true){['search','professorFilter','groupFilter','dayFilter'].forEach(id=>$(id).value='');if(render)renderContent();}
function filtered(){let q=$('search').value.trim().toLowerCase();return source().filter(r=>(!q||[r.professor,r.subject,r.room,...r.groups].join(' ').toLowerCase().includes(q))&&(!$('professorFilter').value||r.professor===$('professorFilter').value)&&(!$('groupFilter').value||r.groups.includes($('groupFilter').value))&&(!$('dayFilter').value||r.day===Number($('dayFilter').value))).sort((a,b)=>a.day-b.day||a.start.localeCompare(b.start)||a.professor.localeCompare(b.professor));}
function setView(v){view=v;for(const type of ['week','list']){$(type+'Button').classList.toggle('active',v===type);$(type+'Button').setAttribute('aria-pressed',String(v===type));}renderContent();}
function badge(r){return r.groups.map(g=>'<span class="badge">'+esc(g)+'</span>').join('');}
function empty(message){return '<div class="empty"><h2>'+message+'</h2><p>'+(records.length===0?'No classes have been published yet.':'Try another search or reset the filters.')+'</p>'+(records.length===0&&isAdmin?'<button class="primary" onclick="openEditor()">? Add a class</button>':'<button onclick="resetFilters()">Reset filters</button>')+'</div>';}
function renderContent(){if(!loaded)return;$('content').className='';renderProfessorSummary();const list=filtered();$('count').textContent=list.length+' classes ? '+new Set(list.map(r=>r.professor)).size+' professors';
if(page==='admin'){$('content').innerHTML=table(list,true);bindRowActions();return;}
if(view==='list'){$('content').innerHTML=table(list,false);bindRowActions();return;}
const minute=t=>Number(t.slice(0,2))*60+Number(t.slice(3)),startHour=Math.min(8,Math.floor((list.length?Math.min(...list.map(r=>minute(r.start))):480)/60)),endHour=Math.max(19,Math.ceil((list.length?Math.max(...list.map(r=>minute(r.end))):1140)/60)),height=(endHour-startHour)*64;
let markup='<div class="calendarwrap"><div class="calendar"><div class="dayhead">Time</div>'+days.slice(1).map((d,i)=>'<div class="dayhead '+(new Date().getDay()===i+1?'today':'')+'">'+d+'</div>').join('')+'<div class="timeline" style="height:'+height+'px">'+Array.from({length:endHour-startHour},(_,i)=>'<span class="timelabel" style="--top:'+i*64+'px">'+String(i+startHour).padStart(2,'0')+':00</span>').join('')+'</div>';
for(let day=1;day<=6;day++){const daily=list.filter(r=>r.day===day),lanes=[];for(const r of daily){let lane=lanes.findIndex(end=>end<=r.start);if(lane<0)lane=lanes.length;lanes[lane]=r.end;r._lane=lane;}const widths=Math.max(1,lanes.length);markup+='<div class="daycolumn" style="height:'+height+'px">'+daily.map(r=>'<button class="classcard '+(r.kind==='Lab'?'lab':r.kind==='Seminar'?'seminar':'')+'" data-detail="'+esc(r.id)+'" style="--top:'+(minute(r.start)-startHour*60)/60*64+'px;--height:'+Math.max(24,(minute(r.end)-minute(r.start))/60*64-4)+'px;left:calc('+r._lane/widths*100+'% + 4px);width:calc('+100/widths+'% - 8px)" aria-label="'+esc(r.subject+', '+r.professor+', '+days[r.day]+' '+r.start+' to '+r.end+', '+r.room+', '+r.groups.join(', '))+'"><span>'+r.start+' / '+r.end+'</span><strong>'+esc(r.subject)+'</strong><span class="prof">'+esc(r.professor)+'</span><span class="room">'+esc(r.room)+' / '+esc(r.groups.join(', '))+'</span></button>').join('')+'</div>';}markup+='</div></div>';$('content').innerHTML=markup;bindRowActions();
}
function table(list,admin){if(!list.length)return empty(admin?'No classes added yet':'No matching classes');return '<div class="tablewrap"><table><thead><tr><th>Day & time</th><th>Subject</th><th>Professor</th><th>Room</th><th>Student groups</th><th>'+(admin?'Actions':'')+'</th></tr></thead><tbody>'+list.map(r=>'<tr><td><strong>'+days[r.day]+'</strong><small>'+r.start+' / '+r.end+'</small></td><td><strong>'+esc(r.subject)+'</strong><small>'+esc(r.kind)+'</small></td><td>'+esc(r.professor)+'</td><td>'+esc(r.room)+'</td><td>'+badge(r)+'</td><td><div class="actions">'+(admin?'<button data-edit="'+esc(r.id)+'">Edit</button><button class="danger" data-delete="'+esc(r.id)+'">Delete</button>':'<button data-detail="'+esc(r.id)+'">Details</button>')+'</div></td></tr>').join('')+'</tbody></table></div>';}
function bindRowActions(){document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showDetails(b.dataset.detail));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(records.find(r=>r.id===b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>confirmDelete(b.dataset.delete));}
function showDetails(id){const r=source().find(r=>r.id===id);$('detailTitle').textContent=r.subject;$('detailBody').innerHTML='<dl class="details">'+[['Professor',r.professor],['Day',days[r.day]],['Time',r.start+' / '+r.end],['Room',r.room],['Groups',r.groups.join(', ')],['Class type',r.kind],['Notes',r.notes||'No additional notes.']].map(([k,v])=>'<dt>'+k+'</dt><dd>'+esc(v)+'</dd>').join('')+'</dl>';$('detailEdit').hidden=!isAdmin;$('detailEdit').onclick=()=>{$('details').close();openEditor(r);};$('details').showModal();}
function openEditor(r){if(!isAdmin){navigate('admin');return;}if(!loaded){toast('Load your timetable before adding classes.');return;}editing=r?.id||null;$('classForm').reset();$('editorTitle').textContent=r?'Edit class':'Add a class';for(const key of ['professor','subject','room','day','start','end','kind','notes'])if(r)$('f'+key).value=r[key]??'';$('fgroups').value=r?r.groups.join(', '):'';$('formError').hidden=true;$('saveButton').disabled=false;$('saveButton').textContent='Save class';$('editor').showModal();$('fprofessor').focus();}
$('classForm').onsubmit=async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.target));raw.day=Number(raw.day);raw.groups=raw.groups.split(',').map(s=>s.trim()).filter(Boolean);$('saveButton').disabled=true;$('saveButton').textContent='Saving...';$('formError').hidden=true;try{const saved=await api('/api/sessions'+(editing?'/'+encodeURIComponent(editing):''),{method:editing?'PUT':'POST',body:JSON.stringify(raw)});if(editing)records=records.map(r=>r.id===editing?saved:r);else records.push(saved);$('editor').close();updateFilters();renderContent();toast(editing?'Class updated.':'Class added.');}catch(error){$('formError').textContent=error.message;$('formError').hidden=false;}finally{$('saveButton').disabled=false;$('saveButton').textContent='Save class';}};
function confirmDelete(id){const r=records.find(r=>r.id===id);$('deleteText').textContent='Remove '+r.subject+' with '+r.professor+' on '+days[r.day]+' at '+r.start+'?';$('deleteError').hidden=true;$('confirmDelete').disabled=false;$('confirmDelete').onclick=async()=>{$('confirmDelete').disabled=true;try{await api('/api/sessions/'+encodeURIComponent(id),{method:'DELETE'});records=records.filter(r=>r.id!==id);$('deleteDialog').close();updateFilters();renderContent();toast('Class deleted.');}catch(e){$('deleteError').textContent=e.message;$('deleteError').hidden=false;}finally{$('confirmDelete').disabled=false;}};$('deleteDialog').showModal();}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function downloadCSV(){const rows=filtered();if(!rows.length){toast('There are no classes to export.');return;}const cell=v=>'"'+String(v??'').replace(/"/g,'""').replace(/^[=+@\t\r-]/,"'$&")+'"';const csv=[['Professor','Subject','Room','Groups','Day','Start','End','Class type','Notes'],...rows.map(r=>[r.professor,r.subject,r.room,r.groups.join(', '),days[r.day],r.start,r.end,r.kind,r.notes])].map(row=>row.map(cell).join(',')).join('\r\n');const a=document.createElement('a');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='faculty-timetable.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(['professors','admin','schedule','rooms'].includes(next)&&next!==page)navigate(next);});

async function refreshAccess(){const access=await getAccess();isAdmin=access.isAdmin;currentUser=access.user;$('adminLabel').textContent=isAdmin?'Admin panel':'Admin sign in';$('signOut').hidden=!currentUser;document.querySelectorAll('[data-admin]').forEach(b=>b.hidden=!isAdmin);if(page==='admin'&&!isAdmin)navigate('professors');else if(loaded)renderContent();}
async function signOut(){try{await logout();await refreshAccess();toast('Signed out.');}catch(e){toast(e.message);}}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginButton').disabled=true;$('loginError').hidden=true;try{await login($('loginEmail').value.trim(),$('loginPassword').value);await refreshAccess();$('loginPassword').value='';if(!isAdmin)throw Error('Signed in, but this account is not an administrator. Ask your administrator to approve it.');$('loginDialog').close();navigate('admin');}catch(e){$('loginError').textContent=e.message;$('loginError').hidden=false;}finally{$('loginButton').disabled=false;}};
Object.assign(window,{navigate,renderContent,resetFilters,setView,downloadCSV,openEditor,load,signOut});
(async()=>{try{await initialize();await refreshAccess();await load();const initial=location.hash.slice(1);if(['professors','admin','schedule','rooms'].includes(initial))navigate(initial);onAuthChange(()=>setTimeout(()=>refreshAccess().catch(e=>toast(e.message)),0));}catch(e){$('status').hidden=false;$('status').className='notice error';$('status').textContent=e.message;$('content').className='empty';$('content').textContent='The timetable is not connected yet. Your administrator needs to finish the Supabase setup.';}})();
function renderProfessorSummary(){
 const section=$('professorSummary');section.hidden=page==='admin';if(page==='admin')return;
 const rows=filtered(),names=[...new Set(rows.map(r=>r.professor))].sort(),chosen=$('professorFilter').value;
 const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Almaty',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());
 const part=name=>parts.find(p=>p.type===name)?.value;
 const dayIndex=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(part('weekday'));
 const now=(dayIndex===0?7:dayIndex)*1440+Number(part('hour'))*60+Number(part('minute'));
 const minute=t=>Number(t.slice(0,2))*60+Number(t.slice(3));
 const nextClass=classes=>classes.map(r=>{let start=r.day*1440+minute(r.start),end=r.day*1440+minute(r.end);const ongoing=start<=now&&end>now;if(end<=now)start+=10080;return {r,start,ongoing};}).sort((a,b)=>a.start-b.start)[0];
 section.innerHTML='<div class="faculty-stats"><span><strong>'+names.length+'</strong> '+(chosen?'professor selected':'professors')+'</span><span><strong>'+rows.length+'</strong> weekly classes</span><span><strong>'+new Set(rows.flatMap(r=>r.groups)).size+'</strong> student groups</span><span class="campus-time">Astana time (UTC+5)</span></div>'+
 (names.length?'<div class="faculty-roster">'+names.map(name=>{const classes=rows.filter(r=>r.professor===name),hours=classes.reduce((sum,r)=>sum+(minute(r.end)-minute(r.start))/60,0),next=nextClass(classes);
 return '<button class="faculty-card '+(chosen===name?'selected':'')+'" data-professor="'+esc(name)+'" aria-pressed="'+(chosen===name)+'"><strong>'+esc(name)+'</strong><span class="faculty-subjects">'+esc([...new Set(classes.map(r=>r.subject))].join(', '))+'</span><span class="faculty-meta">'+classes.length+' classes / '+Number(hours.toFixed(1))+' hours per week</span><span class="faculty-next">'+(next.ongoing?'In progress: ':'Next: ')+days[next.r.day]+' '+next.r.start+' / '+esc(next.r.room)+'</span></button>';
 }).join('')+'</div>':'');
 section.querySelectorAll('[data-professor]').forEach(b=>b.onclick=()=>{$('professorFilter').value=chosen===b.dataset.professor?'':b.dataset.professor;renderContent();});
}
